apiVersion: v1
kind: Secret
metadata:
  name: db-secret            # nombre para referenciarlo desde otros recursos
type: Opaque                 # Opaque = datos genéricos no estructurados
stringData:                  # Escribimos el valor en texto plano; Kubernetes lo codifica
  password: supersecure