# ------------------------------------------------------------
# ConfigMap con parámetros de conexión
# (Ejercicio 05_configmaps, 11_web-app)
# ------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  db-username: "postgres"
  db-name: "pollsdb"
  db-host: "postgres"          # coincide con el nombre del Service